from modules.browser_object_autofill_popup import *
from modules.browser_object_context_menu import *
from modules.browser_object_devtools import *
from modules.browser_object_find_toolbar import *
from modules.browser_object_forget_panel import *
from modules.browser_object_navigation import *
from modules.browser_object_panel_ui import *
from modules.browser_object_reader_view import *
from modules.browser_object_tabbar import *
from modules.browser_object_tracker_panel import *
