from modules.page_object_about_config import *
from modules.page_object_about_downloads import *
from modules.page_object_about_glean import *
from modules.page_object_about_logins import *
from modules.page_object_about_privatebrowsing import *
from modules.page_object_about_profiles import *
from modules.page_object_about_telemetry import *
from modules.page_object_addons_mozilla_org import *
from modules.page_object_autofill_credit_card import *
from modules.page_object_autofill_login import *
from modules.page_object_autofill_test_basic import *
from modules.page_object_customize_firefox import *
from modules.page_object_example_page import *
from modules.page_object_fxa_home import *
from modules.page_object_generics import *
from modules.page_object_google_search import *
from modules.page_object_new_tab import *
from modules.page_object_prefs import *
