from modules.page_object_about_addons import *
from modules.page_object_about_config import *
from modules.page_object_about_glean import *
from modules.page_object_about_logins import *
from modules.page_object_about_newtab import *
from modules.page_object_about_prefs import *
from modules.page_object_about_privatebrowsing import *
from modules.page_object_about_profiles import *
from modules.page_object_about_telemetry import *
from modules.page_object_addons_mozilla_org import *
from modules.page_object_autofill_credit_card import *
from modules.page_object_autofill_test_basic import *
from modules.page_object_example_page import *
from modules.page_object_fxa_home import *
from modules.page_object_generics import *
from modules.page_object_google_search import *
