[tool.pytest.ini_options]
generate_report_on_test = false
addopts = "-vs --html=report.html"
log_cli = true
log_cli_level = "info"
markers = [
    "audio: test is reliant on audio",
    "pynput: test uses pynput package",
    "incident: incident smoke tests",
    "unstable: temporary mark for unstable tests",
    "ci: basic tests to run in ci",
    "locale_de: tests run in DE locale versions",
    "locale_fr: tests run in FR locale versions",
    "locale_gb: tests run in GB locale versions"
]

[tool.ruff]
target-version = "py310"
exclude = [
    "taskcluster"
]

[tool.ruff.lint.per-file-ignores]
"modules/*.py" = ["F403"]
