[tool.pytest.ini_options]
generate_report_on_test = false
addopts = "-vs --html=report.html"
markers = [
    "pynput: test uses pynput package",
    "incident: incident smoke tests"
]

[tool.ruff]
target-version = "py310"
