from .browser_object_autofill_popup import *
from .browser_object_context_menu import *
from .browser_object_devtools import *
from .browser_object_find_toolbar import *
from .browser_object_forget_panel import *
from .browser_object_glean import *
from .browser_object_menu_bar import *
from .browser_object_navigation import *
from .browser_object_panel_ui import *
from .browser_object_print_preview import *
from .browser_object_reader_view import *
from .browser_object_report_broken_site import *
from .browser_object_sidebar import *
from .browser_object_smart_bar import *
from .browser_object_smart_window import *
from .browser_object_split_view import *
from .browser_object_tabbar import *
from .browser_object_translations_panel import *
from .browser_object_trust_panel import *
