name: Check new devedition version

on:
  schedule:
    - cron: "38 */12 * * *"
env:
  LATEST: ""
permissions:
  contents: "write"

jobs:
  Check-DevEdition-Version:
    runs-on: ubuntu-latest
    outputs:
      win_reportable: ${{ steps.reportable.outputs.win }}
      mac_reportable: ${{ steps.reportable.outputs.mac }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check if the run is reportable
        id: reportable
        env:
          TESTRAIL_REPORT: true
          TESTRAIL_BASE_URL: ${{ secrets.TESTRAIL_BASE_URL }}
          TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
          TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
          FX_CHANNEL: "devedition"
        run: |
          pip3 install 'pipenv==2023.11.15';
          pipenv install
          echo win=$(pipenv run python -c 'from modules import testrail_integration as tri; print(tri.reportable("Windows"))') >> "$GITHUB_OUTPUT"
          echo mac=$(pipenv run python -c 'from modules import testrail_integration as tri; print(tri.reportable("Darwin"))') >> "$GITHUB_OUTPUT"
  Run-Win-Smoke:
    needs: Check-DevEdition-Version
    if: ${{ needs.Check-DevEdition-Version.outputs.win_reportable == 'True' }}
    uses: ./.github/workflows/smoke.yml
    with:
      channel: "devedition"
      job_to_run: Smoke-Windows
    secrets: inherit

  Run-Mac-Smoke:
    needs: Check-DevEdition-Version
    if: ${{ needs.Check-DevEdition-Version.outputs.mac_reportable == 'True' }}
    uses: ./.github/workflows/smoke.yml
    with:
      channel: "devedition"
      job_to_run: Smoke-MacOS
    secrets: inherit
