---
name: Full Functional and Glean Tests

on:
  workflow_dispatch:
    inputs:
      win_installer_link:
        description: Windows Firefox installer URL (omit to skip Windows)
        required: false
        type: string

      mac_installer_link:
        description: macOS Firefox installer URL (omit to skip macOS)
        required: false
        type: string

      linux_tarball_link:
        description: Linux Firefox tarball URL (omit to skip Linux)
        required: false
        type: string

      dry_run:
        description: Select tests without downloading Firefox or running tests
        required: false
        default: "false"
        type: string

permissions:
  contents: read

# multiple execution
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  Functional-And-Glean:
    uses: ./.github/workflows/core.yml

    with:
      win_installer_link: ${{ inputs.win_installer_link }}
      mac_installer_link: ${{ inputs.mac_installer_link }}
      linux_tarball_link: ${{ inputs.linux_tarball_link }}
      dry_run: ${{ inputs.dry_run }}
