---
name: L10N output mapping splits

run-name: ${{ github.actor }} is writing L10N mapping splits
on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  Select-Sites-Regions:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    outputs:
      sites_regions: ${{ steps.splits.outputs.sites_regions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: false
          token: ${{ steps.app-token.outputs.token }}
      - name: Select Sites and Regions
        id: splits
        run: |
          python3 scripts/choose_l10n_beta_split.py
